---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - role.yml
  - rolebinding.yml
  - job.yml

configMapGenerator:
  - name: postgres-passwd
    options:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: passwd
    files:
      - configs/playbook.yml
    literals:
      - username=example

images:
  - name: postgres-ansible
    newName: quay.io/toolhippie/ansible
    newTag: "latest"

...
