---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: postgres-passwd
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: passwd

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-passwd

subjects:
  - kind: ServiceAccount
    name: postgres-passwd

...
