---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - service.yml
  - statefulset.yml

commonLabels:
  app.kubernetes.io/component: server

configMapGenerator:
  - name: postgres-init
    files:
      - user.sh=user.sh
  - name: postgres-server
    literals:
      - POSTGRES_GENERAL_DATABASE=test

...
